# Generated by Django 3.2.8 on 2022-01-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره همراه')),
                ('name', models.CharField(max_length=20, verbose_name='نام')),
                ('last_name', models.CharField(max_length=30, verbose_name='نام خانوادگی')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='ایمیل')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد کاربر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('is_admin', models.BooleanField(default=False, verbose_name='دسترسی ادمین')),
                ('deaf', models.BooleanField(default=False, verbose_name='ناشنوا')),
                ('android', models.BooleanField(default=False, verbose_name='کلاس اندروید')),
                ('web', models.BooleanField(default=False, verbose_name='کلاس وب')),
                ('ai', models.BooleanField(default=False, verbose_name='کلاس هوش مصنوعی')),
                ('field', models.CharField(max_length=100, null=True, verbose_name='رشته تحصیلی')),
                ('age', models.CharField(null=True, max_length=300, verbose_name='سن')),
                ('address', models.TextField(null=True, verbose_name='ادرس')),
                ('city', models.CharField(max_length=100, null=True, verbose_name='شهر')),
                ('rezume', models.CharField(blank=True, max_length=300, null=True, verbose_name='لینک رزومه')),
                ('postal_code', models.CharField(blank=True, max_length=300, null=True, verbose_name='کد پستی')),
                ('linked_in', models.CharField(blank=True, max_length=100, null=True, verbose_name='لینکدین')),
                ('static_phone', models.PositiveIntegerField(blank=True, null=True, verbose_name='تلفن ثابت')),
                ('complete_profile', models.BooleanField(default=False, verbose_name='تکمیل پروفایل')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
    ]
