# Generated by Django 3.2.8 on 2021-12-04 13:24

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_zarinpal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='verified_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True),
        ),
    ]
