version: '3'

services:
  web:
    build: .
    command: gunicorn otm_shop.wsgi:application --bind=0.0.0.0:8000 --log-level=debug
    volumes:
      - .:/my_app_dir
    ports:
      - "8001:8000"
    networks:
      - network
    links:
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    volumes:
        - ./volume-mariadb:/var/lib/mysql
    networks:
        - network
    # ports:
        # - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: sfjlkjIUOILUOIRUEROI8098039UOUsfjlkjIUOILUOIRUEROI8098039UOU

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    networks:
      - network
    ports:
      - "8183:80"
    environment:
      PMA_ARBITRARY: 1
    links:
      - mariadb

networks:
    network:
        driver: bridge
