from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .views import *

urlpatterns = [
    path('', index),
#     path('about-us', about_us),
    path('ai-ins', aiins),
    path('android-ins', androidins),
    path('pack-ins', packins),
    path('web-ins', webins),
    path('ai', ai),
    path('android', android),
    path('pack', pack),
#     path('team-us', team_us),
    path('web', web),
    path('term', term),
    path('payment', payment),
    path('verify_coupon', verify_coupon),
    path('validate_payment', validate_payment),
    path('payment_result', payment_result),
    path('accounts/login/', login_view, name='login'),
    path('logout/', logout_view, name="logout"),
    path('dashbord', dashbord, name='dashbord'),
    path('profile/', profile, name='profile'),
    path('profile_edite/', profile_edite, name='profile_edite'),
    path('AI_class', ai_class, name='ai_class'),
    path('android_class', android_class, name='android_class'),
    path('web_class', web_class, name='web_class'),
    path("ai_sessions/<int:session_id>/", ai_class_sessions, name="ai_class_sessions"),
    path("web_sessions/<int:session_id>/", web_class_sessions, name="web_class_sessions"),
    path("android_sessions/<int:session_id>/", android_class_sessions, name="android_class_sessions"),
    path("ai_sessions/<int:session_id>/description", ai_class_sessions_description,
         name="ai_class_sessions_drescription"),
    path("ai_sessions/<int:session_id>/question", ai_class_sessions_question,
         name="ai_class_sessions_question"),
    path("ai_sessions/<int:session_id>/quiz", ai_class_sessions_quiz,
         name="ai_class_sessions_quiz"),

    path("web_sessions/<int:session_id>/description", web_class_sessions_description,
         name="web_class_sessions_drescription"),
    path("web_sessions/<int:session_id>/question", web_class_sessions_question,
         name="web_class_sessions_question"),

    path("android_sessions/<int:session_id>/description", android_class_sessions_description,
         name="android_class_sessions_drescription"),
    path("android_sessions/<int:session_id>/question", android_class_sessions_question,
         name="android_class_sessions_question"),
    # password urls
    # path('change_password', change_password, name="change_password"),
    # path('password_reset', views.PasswordResetView.as_view(), name='password_reset'),
    # path('reset/done', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # path('reset/<uidb64>/<token>', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('password_reset_complete', views.PasswordResetCompleteView.as_view(), name='password_reset_complete')
    path("password_reset", views.password_reset_request, name="password_reset"),
    path("password_reset/done/",
         auth_views.PasswordResetDoneView.as_view(template_name='password/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="password/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path("reset/done/",
         auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'),
         name='password_reset_complete'),
]
# urlpatterns += staticfiles_urlpatterns()
