"""
Django settings for otm_shop project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import mimetypes
mimetypes.add_type("text/css", ".css", True)

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=4yt*66$ach1c64v*bxc5%1dc_=g@&_-=xo3&j=7fg9hq$ob89'
HASHID_FIELD_SALT = SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
ALLOWED_HOSTS = ['cs50x.ir', 'www.cs50x.ir', 'cs50x.ir/winter', 'www.cs50x.ir/winter', 'localhost']


# Application definition



INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_jalali',
    'django_zarinpal',
    'ckeditor',
    'home.apps.HomeConfig',
    'account.apps.AccountConfig',
    'widget_tweaks',
    'django.contrib.humanize'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'otm_shop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'otm_shop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'cs50x',
        'USER': 'root',
        'PASSWORD': 'sfjlkjIUOILUOIRUEROI8098039UOUsfjlkjIUOILUOIRUEROI8098039UOU',
        'HOST': 'mariadb',
        'PORT': '3306',
        'OPTIONS' : {
            'sql_mode' : 'STRICT_ALL_TABLES'
        }
    }
}
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'fa-ir'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
STATICFILES_DIRS = ['/my_app_dir/static',   os.path.join(BASE_DIR, 'static/')]
STATIC_URL = 'static/'

# STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
# STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'account.User'

ZARINPAL_CALLBACK_URL = "https://cs50x.ir/winter/validate_payment"

ZARINPAL_VERIFY_TRANSACTION_VIEW = ZARINPAL_CALLBACK_URL

ZARINPAL_SIMULATION = False

ZARINPAL_MERCHANT_ID = "de532b57-0df0-45c5-8047-3143502165bb"

SIGNAL_NUMBER = "5000439800"

SIGNAL_TOKEN = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjdiYzEzNjc5NzlkMjM3MjFiZDZmNzlkOGEwNWMzMDgzZjdhMjNhMzE2ZGVjZDMzY2Q5ODRmNDQ1MzRjMDM2YWNmNzJkMzJiYjMzZjI2YzE2In0.eyJhdWQiOiIxIiwianRpIjoiN2JjMTM2Nzk3OWQyMzcyMWJkNmY3OWQ4YTA1YzMwODNmN2EyM2EzMTZkZWNkMzNjZDk4NGY0NDUzNGMwMzZhY2Y3MmQzMmJiMzNmMjZjMTYiLCJpYXQiOjE2Mzg2MzY4NDEsIm5iZiI6MTYzODYzNjg0MSwiZXhwIjoxNjcwMTcyODQxLCJzdWIiOiI4ODc4Iiwic2NvcGVzIjpbXX0.bcLJBAXbwrx4Btj811CJcYVBbirbeSOvFM2xax4P-x4PLAKfsAiG_VPr5Z7OY3QSDxva8BiDVj3XWK_I3jESh43hcCEDztandVHi5l57-JZuNU_IkQ8iYzGtiNkS5S57qnYrZNYIuWQd5UejsCLN8mu2fi7JhQfaHD-9bSEIq4xJUGPHhuJN1awfEu9p5A5YOi7abF7tiaWG2WXjK4QSHDTw8pJRHgD3qZfC1L0KDqdHgQyIuDpEhJcM3-aJZpWtM0amrw7gsFI5C8xXcCQ5UTvhXMhnlj-vdTsy8HSG-4wG_SM7hNMhleiFhCMJ6urpZXJUzDMR9W2w6rd3YAsELP4iv_xqT2DjDAwks5u9IwrVsuI-ugtGajj6f4KZkNiUiDYaDBZROpuaepgA59nxYKW1utiPpkSIqpGbKZuKtHfxTPMxxEbpBPYqNmlJ4YT_U2L17Nmkqs6-46Jr2b4Sf3iD0jfXCUBxbabwKlZqzVL2H1030l4rydy1oPpg1t8IMMZSoYX9i_Tq9597y81h4kiJYfsmVeAbD_8kF7sfNDHYepRfh0NvIM3D3vVaq-ZbIUvjCS_O1O0a_gAfGieJgqQg7hz3cNAOWRj6cKldAYCbaDp-XmTEserGNoJhYEviEwoSsA48RB0wiiYc3aOp8rPY6jAClnMjByQ3Mst95bM"
SE_X_FORWARDED_HOST = True
FORCE_SCRIPT_NAME = '/winter'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_TIMEOUT = 3
EAMIL_ADDRESS = "hello@cs50x.ir"
EMAIL_USE_SSL = False
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST = "smtp-relay.sendinblue.com"
EMAIL_HOST_USER = 'cs50xiran@gmail.com'
EMAIL_HOST_PASSWORD = '2kDM3zPn5Sag1CEf'
