# Generated by Django 3.2.8 on 2021-12-03 18:35

from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_zarinpal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128)),
                ('amount', models.IntegerField()),
                ('type', models.CharField(choices=[('OT', 'OneTime'), ('LT', 'Limited'), ('FR', 'Free')], max_length=64)),
                ('max_use', models.IntegerField(default=0, null=True)),
                ('is_expired', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=256)),
                ('lastname', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('price', models.IntegerField()),
                ('type', models.CharField(choices=[('android', 'Android'), ('ai', 'Artificial Intelligence'), ('web', 'Web'), ('pack', 'Pack')], max_length=64)),
                ('customers', models.ManyToManyField(to='home.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('track_number', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Transaction has just started'), ('FAILED', 'Transaction has failed'), ('SUCCESS', 'Transaction has successfully done')], default='PENDING', max_length=100)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.customer')),
                ('cuopon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.coupon')),
                ('customers', models.ManyToManyField(blank=True, related_name='customers', to='home.Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.product')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_zarinpal.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='orders', to='home.Order'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.customer'),
        ),
    ]
