# Generated by Django 3.2.8 on 2021-12-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_customer_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting_AI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=1000, null=True, verbose_name='تیتر دوره')),
                ('course_description', models.CharField(max_length=1000, null=True, verbose_name='توضیحات زیر تیتر دوره')),
                ('left_button', models.CharField(max_length=256, null=True, verbose_name='دکمه سمت چپ')),
                ('right_button', models.CharField(max_length=256, null=True, verbose_name='دکمه سمت راست')),
                ('course_feature_title1', models.CharField(max_length=256, null=True, verbose_name='تیتر ویژگی اول')),
                ('course_feature_description1', models.CharField(max_length=256, null=True, verbose_name='توضیحات ویژگی اول')),
            ],
        ),
    ]
