# Generated by Django 3.2.8 on 2021-12-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_setting_ai'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting_ai',
            name='course_feature_description2',
            field=models.CharField(max_length=256, null=True, verbose_name='توضیحات ویژگی دوم'),
        ),
        migrations.AddField(
            model_name='setting_ai',
            name='course_feature_description3',
            field=models.CharField(max_length=256, null=True, verbose_name='توضیحات ویژگی سوم'),
        ),
        migrations.AddField(
            model_name='setting_ai',
            name='course_feature_title2',
            field=models.CharField(max_length=256, null=True, verbose_name='تیتر ویژگی دوم'),
        ),
        migrations.AddField(
            model_name='setting_ai',
            name='course_feature_title3',
            field=models.CharField(max_length=256, null=True, verbose_name='تیتر ویژگی سوم'),
        ),
    ]
