# Generated by Django 3.2.8 on 2021-12-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20211204_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting_ai',
            name='course_feature_description4',
            field=models.CharField(max_length=256, null=True, verbose_name='توضیحات ویژگی چهارم'),
        ),
        migrations.AddField(
            model_name='setting_ai',
            name='course_feature_title4',
            field=models.CharField(max_length=256, null=True, verbose_name='تیتر ویژگی چهارم'),
        ),
        migrations.AddField(
            model_name='setting_ai',
            name='course_skill_topic',
            field=models.CharField(max_length=256, null=True, verbose_name='عنوان دوره'),
        ),
        migrations.AddField(
            model_name='setting_ai',
            name='course_topic',
            field=models.CharField(max_length=256, null=True, verbose_name='تیتر سرفصل دوره'),
        ),
        migrations.AddField(
            model_name='setting_ai',
            name='david_video_description',
            field=models.CharField(max_length=256, null=True, verbose_name='توضیحات زیر ویدئو david'),
        ),
        migrations.AddField(
            model_name='setting_ai',
            name='david_video_description_under_register',
            field=models.CharField(max_length=256, null=True, verbose_name='توضیحات روبه روی ویدئو david'),
        ),
        migrations.AddField(
            model_name='setting_ai',
            name='david_video_title',
            field=models.CharField(max_length=256, null=True, verbose_name='تیتر زیر ویدئو david'),
        ),
        migrations.AddField(
            model_name='setting_ai',
            name='david_video_title_under_register',
            field=models.CharField(max_length=256, null=True, verbose_name='تیتر روبه روی ویدئو david'),
        ),
        migrations.AddField(
            model_name='setting_ai',
            name='skill_description1',
            field=models.CharField(max_length=256, null=True, verbose_name='توضیحات مهارت اول'),
        ),
        migrations.AddField(
            model_name='setting_ai',
            name='skill_description2',
            field=models.CharField(max_length=256, null=True, verbose_name='توضیحات مهارت دوم'),
        ),
        migrations.AddField(
            model_name='setting_ai',
            name='skill_description3',
            field=models.CharField(max_length=256, null=True, verbose_name='توضیحات مهارت سوم'),
        ),
        migrations.AddField(
            model_name='setting_ai',
            name='skill_description4',
            field=models.CharField(max_length=256, null=True, verbose_name='توضیحات مهارت چهارم'),
        ),
        migrations.AddField(
            model_name='setting_ai',
            name='skills_title',
            field=models.CharField(max_length=256, null=True, verbose_name='تیتر مهارت ها'),
        ),
        migrations.AddField(
            model_name='setting_ai',
            name='skills_title1',
            field=models.CharField(max_length=256, null=True, verbose_name='تیتر مهارت اول'),
        ),
        migrations.AddField(
            model_name='setting_ai',
            name='skills_title2',
            field=models.CharField(max_length=256, null=True, verbose_name='تیتر مهارت دوم'),
        ),
        migrations.AddField(
            model_name='setting_ai',
            name='skills_title3',
            field=models.CharField(max_length=256, null=True, verbose_name='تیتر مهارت سوم'),
        ),
        migrations.AddField(
            model_name='setting_ai',
            name='skills_title4',
            field=models.CharField(max_length=256, null=True, verbose_name='تیتر مهارت چهارم'),
        ),
        migrations.AddField(
            model_name='setting_ai',
            name='suitable_for_title',
            field=models.CharField(max_length=256, null=True, verbose_name='تیتر دوره مناسب چه افرادی است'),
        ),
        migrations.AddField(
            model_name='setting_ai',
            name='suitable_for_title1',
            field=models.CharField(max_length=256, null=True, verbose_name='توضیح اول'),
        ),
        migrations.AddField(
            model_name='setting_ai',
            name='suitable_for_title2',
            field=models.CharField(max_length=256, null=True, verbose_name='توضیح دوم'),
        ),
        migrations.AddField(
            model_name='setting_ai',
            name='suitable_for_title3',
            field=models.CharField(max_length=256, null=True, verbose_name='توضیح سوم'),
        ),
        migrations.AddField(
            model_name='setting_ai',
            name='suitable_for_title4',
            field=models.CharField(max_length=256, null=True, verbose_name='توضیح چهارم'),
        ),
        migrations.AddField(
            model_name='setting_ai',
            name='teacher_description',
            field=models.CharField(max_length=1000, null=True, verbose_name='توضیحات مدرس'),
        ),
        migrations.AddField(
            model_name='setting_ai',
            name='teacher_name',
            field=models.CharField(max_length=256, null=True, verbose_name='اسم مدرس'),
        ),
        migrations.AddField(
            model_name='setting_ai',
            name='title_of_document',
            field=models.CharField(max_length=256, null=True, verbose_name='تیتر مدرک هاروارد'),
        ),
        migrations.AddField(
            model_name='setting_ai',
            name='who_are_we_description1',
            field=models.CharField(max_length=256, null=True, verbose_name='توضیحات خط اول ما کی هستیم'),
        ),
        migrations.AddField(
            model_name='setting_ai',
            name='who_are_we_description2',
            field=models.CharField(max_length=256, null=True, verbose_name='توضیحات خط دوم ما کی هستیم'),
        ),
        migrations.AddField(
            model_name='setting_ai',
            name='who_are_we_title',
            field=models.CharField(max_length=256, null=True, verbose_name='تیتر ما کی هستیم؟'),
        ),
    ]
