# Generated by Django 3.2.8 on 2021-12-05 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20211204_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting_ai',
            options={'verbose_name': 'تنظیمات لندینگ هوش مصنوعی', 'verbose_name_plural': 'مدیریت تنظیمات لندینگ هوش مصنوعی'},
        ),
        migrations.AddField(
            model_name='setting_ai',
            name='left_course_description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='توضیحات دوره سمت چپ انتهای سایت'),
        ),
        migrations.AddField(
            model_name='setting_ai',
            name='left_course_price',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='قیمت دوره سمت چپ انتهای سایت'),
        ),
        migrations.AddField(
            model_name='setting_ai',
            name='left_course_title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='تیتر دوره سمت چپ انتهای سایت'),
        ),
        migrations.AddField(
            model_name='setting_ai',
            name='right_course_description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='توضیحات دوره سمت راست انتهای سایت'),
        ),
        migrations.AddField(
            model_name='setting_ai',
            name='right_course_price',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='قیمت دوره سمت راست انتهای سایت'),
        ),
        migrations.AddField(
            model_name='setting_ai',
            name='right_course_title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='تیتر دوره سمت راست انتهای سایت'),
        ),
    ]
