# Generated by Django 3.2.8 on 2021-12-05 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_setting_ai_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting_ai',
            name='course_title',
            field=models.CharField(blank=True, default=False, max_length=1000, verbose_name='تیتر دوره'),
        ),
    ]
