# Generated by Django 3.2.8 on 2021-12-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_setting_ai_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting_ai',
            name='course_description',
            field=models.CharField(blank=True, default=False, max_length=1000, verbose_name='توضیحات زیر تیتر دوره'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='course_feature_description1',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات ویژگی اول'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='course_feature_description2',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات ویژگی دوم'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='course_feature_description3',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات ویژگی سوم'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='course_feature_description4',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات ویژگی چهارم'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='course_feature_title1',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='تیتر ویژگی اول'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='course_feature_title2',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='تیتر ویژگی دوم'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='course_feature_title3',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='تیتر ویژگی سوم'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='course_feature_title4',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='تیتر ویژگی چهارم'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='course_skill_topic',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='عنوان دوره'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='course_topic',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='تیتر سرفصل دوره'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='david_video_description',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات زیر ویدئو david'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='david_video_description_under_register',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات روبه روی ویدئو david'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='david_video_title',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='تیتر زیر ویدئو david'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='david_video_title_under_register',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='تیتر روبه روی ویدئو david'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='left_button',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='دکمه سمت چپ'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='left_course_description',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات دوره سمت چپ انتهای سایت'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='left_course_price',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='قیمت دوره سمت چپ انتهای سایت'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='left_course_title',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='تیتر دوره سمت چپ انتهای سایت'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='right_button',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='دکمه سمت راست'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='right_course_description',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات دوره سمت راست انتهای سایت'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='right_course_price',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='قیمت دوره سمت راست انتهای سایت'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='right_course_title',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='تیتر دوره سمت راست انتهای سایت'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='skill_description1',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات مهارت اول'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='skill_description2',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات مهارت دوم'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='skill_description3',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات مهارت سوم'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='skill_description4',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات مهارت چهارم'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='skills_title',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='تیتر مهارت ها'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='skills_title1',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='تیتر مهارت اول'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='skills_title2',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='تیتر مهارت دوم'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='skills_title3',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='تیتر مهارت سوم'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='skills_title4',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='تیتر مهارت چهارم'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='suitable_for_title',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='تیتر دوره مناسب چه افرادی است'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='suitable_for_title1',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیح اول'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='suitable_for_title2',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیح دوم'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='suitable_for_title3',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیح سوم'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='suitable_for_title4',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیح چهارم'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='teacher_description',
            field=models.CharField(blank=True, default=False, max_length=1000, verbose_name='توضیحات مدرس'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='teacher_name',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='اسم مدرس'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='title_of_document',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='تیتر مدرک هاروارد'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='who_are_we_description1',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات خط اول ما کی هستیم'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='who_are_we_description2',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات خط دوم ما کی هستیم'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='who_are_we_title',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='تیتر ما کی هستیم؟'),
        ),
    ]
