# Generated by Django 3.2.8 on 2021-12-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20211205_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting_ai',
            name='david_video_description',
        ),
        migrations.AddField(
            model_name='setting_ai',
            name='david_video_description1',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات خط اول زیر ویدئو david'),
        ),
        migrations.AddField(
            model_name='setting_ai',
            name='david_video_description2',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات خط دوم زیر ویدئو david'),
        ),
    ]
