# Generated by Django 3.2.8 on 2021-12-05 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20211205_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting_ai',
            name='skill_description1_1',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات خط دوم مهارت اول'),
        ),
        migrations.AddField(
            model_name='setting_ai',
            name='skill_description2_2',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات خط دوم مهارت دوم'),
        ),
        migrations.AddField(
            model_name='setting_ai',
            name='skill_description3_3',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات خط دوم مهارت سوم'),
        ),
        migrations.AddField(
            model_name='setting_ai',
            name='skill_description4_4',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات خط دوم مهارت چهارم'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='skill_description1',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات خط اول مهارت اول'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='skill_description2',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات خط اول مهارت دوم'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='skill_description3',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات خط اول مهارت سوم'),
        ),
        migrations.AlterField(
            model_name='setting_ai',
            name='skill_description4',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات خط اول مهارت چهارم'),
        ),
    ]
