# Generated by Django 3.2.8 on 2021-12-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20211205_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='setting_ai_faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, default=False, max_length=1000, verbose_name='سوال متداول')),
                ('answer', models.CharField(blank=True, default=False, max_length=1000, verbose_name='پاسخ سوال متداول')),
            ],
            options={
                'verbose_name': 'تنظیمات سوالات متداول لندینگ هوش مصنوعی',
                'verbose_name_plural': 'مدیریت تنظیمات سوالات متداول لندینگ هوش مصنوعی',
            },
        ),
    ]
