# Generated by Django 3.2.8 on 2021-12-05 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_setting_ai_faq'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='setting_ai_faq',
            new_name='ai_faq',
        ),
    ]
