# Generated by Django 3.2.8 on 2021-12-05 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_rename_setting_ai_faq_ai_faq'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ai_faq',
            new_name='Setting_AI_Faq',
        ),
    ]
