# Generated by Django 3.2.8 on 2021-12-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_setting_android'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting_Web',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(blank=True, default=False, max_length=1000, verbose_name='تیتر دوره')),
                ('course_description', models.CharField(blank=True, default=False, max_length=1000, verbose_name='توضیحات زیر تیتر دوره')),
                ('left_button', models.CharField(blank=True, default=False, max_length=256, verbose_name='دکمه سمت چپ')),
                ('right_button', models.CharField(blank=True, default=False, max_length=256, verbose_name='دکمه سمت راست')),
                ('course_feature_title1', models.CharField(blank=True, default=False, max_length=256, verbose_name='تیتر ویژگی اول')),
                ('course_feature_description1', models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات ویژگی اول')),
                ('course_feature_title2', models.CharField(blank=True, default=False, max_length=256, verbose_name='تیتر ویژگی دوم')),
                ('course_feature_description2', models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات ویژگی دوم')),
                ('course_feature_title3', models.CharField(blank=True, default=False, max_length=256, verbose_name='تیتر ویژگی سوم')),
                ('course_feature_description3', models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات ویژگی سوم')),
                ('course_feature_title4', models.CharField(blank=True, default=False, max_length=256, verbose_name='تیتر ویژگی چهارم')),
                ('course_feature_description4', models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات ویژگی چهارم')),
                ('david_video_title', models.CharField(blank=True, default=False, max_length=256, verbose_name='تیتر زیر ویدئو david')),
                ('david_video_description1', models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات خط اول زیر ویدئو david')),
                ('david_video_description2', models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات خط دوم زیر ویدئو david')),
                ('skills_title', models.CharField(blank=True, default=False, max_length=256, verbose_name='تیتر مهارت ها')),
                ('skills_title1', models.CharField(blank=True, default=False, max_length=256, verbose_name='تیتر مهارت اول')),
                ('skill_description1', models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات خط اول مهارت اول')),
                ('skill_description1_1', models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات خط دوم مهارت اول')),
                ('skills_title2', models.CharField(blank=True, default=False, max_length=256, verbose_name='تیتر مهارت دوم')),
                ('skill_description2', models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات خط اول مهارت دوم')),
                ('skill_description2_2', models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات خط دوم مهارت دوم')),
                ('skills_title3', models.CharField(blank=True, default=False, max_length=256, verbose_name='تیتر مهارت سوم')),
                ('skill_description3', models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات خط اول مهارت سوم')),
                ('skill_description3_3', models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات خط دوم مهارت سوم')),
                ('skills_title4', models.CharField(blank=True, default=False, max_length=256, verbose_name='تیتر مهارت چهارم')),
                ('skill_description4', models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات خط اول مهارت چهارم')),
                ('skill_description4_4', models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات خط دوم مهارت چهارم')),
                ('course_topic', models.CharField(blank=True, default=False, max_length=256, verbose_name='تیتر سرفصل دوره')),
                ('course_skill_topic', models.CharField(blank=True, default=False, max_length=256, verbose_name='عنوان دوره')),
                ('teacher_name', models.CharField(blank=True, default=False, max_length=256, verbose_name='اسم مدرس')),
                ('teacher_description', models.CharField(blank=True, default=False, max_length=1000, verbose_name='توضیحات مدرس')),
                ('suitable_for_title', models.CharField(blank=True, default=False, max_length=256, verbose_name='تیتر دوره مناسب چه افرادی است')),
                ('suitable_for_title1', models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیح اول')),
                ('suitable_for_title2', models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیح دوم')),
                ('suitable_for_title3', models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیح سوم')),
                ('suitable_for_title4', models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیح چهارم')),
                ('title_of_document', models.CharField(blank=True, default=False, max_length=256, verbose_name='تیتر مدرک هاروارد')),
                ('david_video_title_under_register', models.CharField(blank=True, default=False, max_length=256, verbose_name='تیتر روبه روی ویدئو david')),
                ('david_video_description_under_register', models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات روبه روی ویدئو david')),
                ('who_are_we_title', models.CharField(blank=True, default=False, max_length=256, verbose_name='تیتر ما کی هستیم؟')),
                ('who_are_we_description1', models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات خط اول ما کی هستیم')),
                ('who_are_we_description2', models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات خط دوم ما کی هستیم')),
                ('right_course_title', models.CharField(blank=True, default=False, max_length=256, verbose_name='تیتر دوره سمت راست انتهای سایت')),
                ('right_course_description', models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات دوره سمت راست انتهای سایت')),
                ('right_course_price', models.CharField(blank=True, default=False, max_length=256, verbose_name='قیمت دوره سمت راست انتهای سایت')),
                ('left_course_title', models.CharField(blank=True, default=False, max_length=256, verbose_name='تیتر دوره سمت چپ انتهای سایت')),
                ('left_course_description', models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات دوره سمت چپ انتهای سایت')),
                ('left_course_price', models.CharField(blank=True, default=False, max_length=256, verbose_name='قیمت دوره سمت چپ انتهای سایت')),
            ],
            options={
                'verbose_name': 'تنظیمات لندینگ اندروید',
                'verbose_name_plural': 'مدیریت تنظیمات لندینگ اندروید',
            },
        ),
        migrations.AlterModelOptions(
            name='setting_android',
            options={'verbose_name': 'تنظیمات لندینگ اندروید', 'verbose_name_plural': 'مدیریت تنظیمات لندینگ اندروید'},
        ),
    ]
