# Generated by Django 3.2.8 on 2021-12-06 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20211205_1724'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Setting_AI_Faq',
        ),
    ]
