# Generated by Django 3.2.8 on 2021-12-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_delete_setting_ai_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting_pack',
            name='skill_description1',
        ),
        migrations.RemoveField(
            model_name='setting_pack',
            name='skill_description1_1',
        ),
        migrations.RemoveField(
            model_name='setting_pack',
            name='skill_description2',
        ),
        migrations.RemoveField(
            model_name='setting_pack',
            name='skill_description2_2',
        ),
        migrations.RemoveField(
            model_name='setting_pack',
            name='skill_description3',
        ),
        migrations.RemoveField(
            model_name='setting_pack',
            name='skill_description3_3',
        ),
        migrations.RemoveField(
            model_name='setting_pack',
            name='skill_description4',
        ),
        migrations.RemoveField(
            model_name='setting_pack',
            name='skill_description4_4',
        ),
        migrations.RemoveField(
            model_name='setting_pack',
            name='skills_title',
        ),
        migrations.RemoveField(
            model_name='setting_pack',
            name='skills_title1',
        ),
        migrations.RemoveField(
            model_name='setting_pack',
            name='skills_title2',
        ),
        migrations.RemoveField(
            model_name='setting_pack',
            name='skills_title3',
        ),
        migrations.RemoveField(
            model_name='setting_pack',
            name='skills_title4',
        ),
        migrations.AddField(
            model_name='setting_pack',
            name='course_ai_description1',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیح خط اول سرفصل هوش مصنوعی'),
        ),
        migrations.AddField(
            model_name='setting_pack',
            name='course_ai_description2',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیح خط دوم سر فصل هوش مصنوعی'),
        ),
        migrations.AddField(
            model_name='setting_pack',
            name='course_ai_description3',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیح خط سوم سرفصل هوش مصنوعی'),
        ),
        migrations.AddField(
            model_name='setting_pack',
            name='course_ai_description4',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیح خط چهارم سرفصل هوش مصنوعی'),
        ),
        migrations.AddField(
            model_name='setting_pack',
            name='course_ai_title',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='تیتر دوره هوش مصنوعی زیر سرفصل'),
        ),
        migrations.AddField(
            model_name='setting_pack',
            name='course_android_description1',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیح خط اول سرفصل وب'),
        ),
        migrations.AddField(
            model_name='setting_pack',
            name='course_android_description2',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیح خط دوم سر فصل وب'),
        ),
        migrations.AddField(
            model_name='setting_pack',
            name='course_android_description3',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیح خط سوم سرفصل وب'),
        ),
        migrations.AddField(
            model_name='setting_pack',
            name='course_android_description4',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیح خط چهارم سرفصل وب'),
        ),
        migrations.AddField(
            model_name='setting_pack',
            name='course_android_title',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='تیتر دوره اندروید زیر سرفصل'),
        ),
        migrations.AddField(
            model_name='setting_pack',
            name='course_feature_description1',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات ویژگی اول'),
        ),
        migrations.AddField(
            model_name='setting_pack',
            name='course_feature_description2',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات ویژگی دوم'),
        ),
        migrations.AddField(
            model_name='setting_pack',
            name='course_feature_description3',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات ویژگی سوم'),
        ),
        migrations.AddField(
            model_name='setting_pack',
            name='course_feature_description4',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات ویژگی چهارم'),
        ),
        migrations.AddField(
            model_name='setting_pack',
            name='course_feature_title1',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='تیتر ویژگی اول'),
        ),
        migrations.AddField(
            model_name='setting_pack',
            name='course_feature_title2',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='تیتر ویژگی دوم'),
        ),
        migrations.AddField(
            model_name='setting_pack',
            name='course_feature_title3',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='تیتر ویژگی سوم'),
        ),
        migrations.AddField(
            model_name='setting_pack',
            name='course_feature_title4',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='تیتر ویژگی چهارم'),
        ),
        migrations.AddField(
            model_name='setting_pack',
            name='course_topic',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='تیتر سرفصل دوره'),
        ),
        migrations.AddField(
            model_name='setting_pack',
            name='course_under_description',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات زیر سر فصل دوره'),
        ),
        migrations.AddField(
            model_name='setting_pack',
            name='course_web_description1',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیح خط اول سرفصل وب'),
        ),
        migrations.AddField(
            model_name='setting_pack',
            name='course_web_description2',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیح خط دوم سر فصل وب'),
        ),
        migrations.AddField(
            model_name='setting_pack',
            name='course_web_description3',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیح خط سوم سرفصل وب'),
        ),
        migrations.AddField(
            model_name='setting_pack',
            name='course_web_description4',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیح خط چهارم سرفصل وب'),
        ),
        migrations.AddField(
            model_name='setting_pack',
            name='course_web_title',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='تیتر دوره وب زیر سر فصل'),
        ),
        migrations.AddField(
            model_name='setting_pack',
            name='first_teacher_button',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='متن داخل دکمه اولین مدرس'),
        ),
        migrations.AddField(
            model_name='setting_pack',
            name='first_teacher_description',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات زیر نام اولین مدرس'),
        ),
        migrations.AddField(
            model_name='setting_pack',
            name='first_teacher_name',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='نام اولین مدرس'),
        ),
        migrations.AddField(
            model_name='setting_pack',
            name='second_teacher_button',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='متن داخل دکمه دومین مدرس'),
        ),
        migrations.AddField(
            model_name='setting_pack',
            name='second_teacher_description',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات زیر نام دومین مدرس'),
        ),
        migrations.AddField(
            model_name='setting_pack',
            name='second_teacher_name',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='نام دومین مدرس'),
        ),
        migrations.AddField(
            model_name='setting_pack',
            name='third_teacher_button',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='متن داخل دکمه سومین مدرس'),
        ),
        migrations.AddField(
            model_name='setting_pack',
            name='third_teacher_description',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات زیر نام سومین مدرس'),
        ),
        migrations.AddField(
            model_name='setting_pack',
            name='third_teacher_name',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='نام سومین مدرس'),
        ),
    ]
