# Generated by Django 3.2.8 on 2021-12-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20211207_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting_pack',
            name='course_under_description',
        ),
        migrations.AddField(
            model_name='setting_pack',
            name='course_under_description1',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات زیر سر فصل دوره خط اول'),
        ),
        migrations.AddField(
            model_name='setting_pack',
            name='course_under_description2',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیحات زیر سر فصل دوره خط دوم'),
        ),
    ]
