# Generated by Django 3.2.8 on 2021-12-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_auto_20211207_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting_pack',
            name='course_android_description1',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیح خط اول سرفصل اندروید'),
        ),
        migrations.AlterField(
            model_name='setting_pack',
            name='course_android_description2',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیح خط دوم سر فصل اندروید'),
        ),
        migrations.AlterField(
            model_name='setting_pack',
            name='course_android_description3',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیح خط سوم سرفصل اندروید'),
        ),
        migrations.AlterField(
            model_name='setting_pack',
            name='course_android_description4',
            field=models.CharField(blank=True, default=False, max_length=256, verbose_name='توضیح خط چهارم سرفصل اندروید'),
        ),
    ]
